name: Scheduled Scrape

on:
  schedule:
    # Ejecuta los 7 días de la semana en horarios UTC:
    - cron: '0 3 * * *'    # 3:00 AM
    - cron: '0 7 * * *'    # 7:00 AM
    - cron: '0 11 * * *'   # 11:00 AM (Mediodía)
    - cron: '45 14 * * *'  # 2:45 PM
    - cron: '15 18 * * *'  # 6:15 PM
    - cron: '0 23 * * *'   # 11:00 PM (Noche - Especial)
    
env:
  BASE_URL: ${{ secrets.BACKEND_BASE_URL }} # Obtiene el valor del Secret de GitHub
  
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger scrape endpoint
        run: |
          # Obtener la hora actual en formato 0-23 (UTC)
          CURRENT_HOUR=$(date +%H)
          
          # Por defecto bcv es false
          BCV_PARAM="false"
          
          # Si es la ejecución de las 11 PM (Hora 23), activamos bcv
          if [ "$CURRENT_HOUR" -eq "23" ]; then
            BCV_PARAM="true"
            echo "🕒 Ejecución de las 11 PM detectada. Activando BCV."
          fi

          URL_ENDPOINT="$BASE_URL/api/venezuela/update-currencies?bcv=$BCV_PARAM&yadio=true&binance=true"

          echo "Ejecutando solicitud PUT a: $URL_ENDPOINT"
          
          HTTP_CODE=$(curl -X PUT -s -S -o /dev/null -w "%{http_code}" "$URL_ENDPOINT")

          echo "Código de estado HTTP recibido: $HTTP_CODE"

          if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 300 ]; then
            echo "✅ Solicitud PUT completada exitosamente (Código $HTTP_CODE)."
          else
            # Falla el job si el código de estado no es 2xx
            echo "❌ ERROR: La solicitud PUT falló. Código de estado: $HTTP_CODE"
            exit 1
          fi
